import { config } from 'dotenv';

config({ path: `.env` }); 

export const { PORT,
    NODE_ENV,
    TWILIO_PHONE_NUMBER,
    TWILIO_AUTH_TOKEN,
    TWILIO_ACCOUNT_SID,
    DATABASE_URL,
    JWT_SECRET,
    JWT_EXPIRES_IN,
    JWT_REFRESH_SECRET,
    REGULATIONS_MIN_LICENSE_LENGTH,
    REGULATIONS_REQUIRED_FIELDS,
    REGULATIONS_ALLOWED_REGIONS,
} = process.env; 